# Generated by Django 4.1 on 2022-09-05 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_newuser_address_newuser_city_newuser_phone_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='profile_photo',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
